import type { LoomspaceState } from './types';

export const sampleState: LoomspaceState = {
  workspaceId: 'loomspace-demo',
  title: 'Loomspace Demo Loom',
  selectedId: 'loom-main',
  zoom: 1,
  panX: 0,
  panY: 0,
  densityOverlay: true,
  version: 1,
  threads: [
    { id: 'warp-core', title: 'Primary warp', color: '#7cf7c2', status: 'active' },
    { id: 'side-ux', title: 'Canvas mechanics', color: '#7ea8ff', status: 'stitch-ready' },
    { id: 'side-ai', title: 'AI extension contract', color: '#d48bff', status: 'active' },
  ],
  nodes: [
    {
      id: 'loom-main',
      kind: 'loom',
      title: 'Loomspace',
      summary: 'The workspace where the fabric stays readable under pressure.',
      x: 520,
      y: 250,
      confidence: 'high',
      provenance: ['README core idea'],
      pinned: true,
    },
    {
      id: 'warp-primary',
      kind: 'warp',
      threadId: 'warp-core',
      title: 'Primary context stream',
      summary: 'Keep the main line visually dominant and easy to stitch back into.',
      x: 300,
      y: 160,
      confidence: 'high',
      provenance: ['Vision: primary stream stays dominant'],
    },
    {
      id: 'thread-mechanics',
      kind: 'thread',
      threadId: 'side-ux',
      title: 'Canvas mechanics',
      summary: 'Drag, inspect, stitch, collapse. No mystery gestures.',
      x: 180,
      y: 360,
      confidence: 'high',
      provenance: ['MVP priority: mechanics before bells and whistles'],
    },
    {
      id: 'thread-ai',
      kind: 'thread',
      threadId: 'side-ai',
      title: 'AI extension surface',
      summary: 'Python and TypeScript packages expose the same plugin contract.',
      x: 760,
      y: 150,
      confidence: 'medium',
      provenance: ['User preference: AI community will extend it'],
    },
    {
      id: 'idea-fabric',
      kind: 'idea',
      title: 'Fabric of truth',
      summary: 'Claims, evidence, and contradictions are rendered as weave, not charts.',
      x: 760,
      y: 360,
      confidence: 'high',
      provenance: ['Conversation: canvas should stand out'],
    },
    {
      id: 'evidence-one',
      kind: 'evidence',
      threadId: 'side-ux',
      title: 'Every node can answer why',
      summary: 'Provenance is attached to every object and remains visible in the inspector.',
      x: 320,
      y: 520,
      confidence: 'high',
      provenance: ['MVP: provenance everywhere'],
    },
    {
      id: 'stitch-one',
      kind: 'stitch',
      threadId: 'warp-core',
      title: 'Stitch: mechanics-first build',
      summary: 'The MVP is a working slice, not a pile of planned glitter.',
      x: 560,
      y: 520,
      confidence: 'medium',
      provenance: ['User asked to build and ship in stages'],
    },
    {
      id: 'decision-one',
      kind: 'decision',
      title: 'Decision: build the canvas first',
      summary: 'Treat the canvas as the product; let AI write the fabric underneath.',
      x: 900,
      y: 540,
      confidence: 'high',
      provenance: ['Assistant recommendation in convo'],
    },
  ],
  edges: [
    { id: 'edge-1', from: 'loom-main', to: 'warp-primary', kind: 'supports', label: 'anchors' },
    { id: 'edge-2', from: 'loom-main', to: 'thread-mechanics', kind: 'links', label: 'includes' },
    { id: 'edge-3', from: 'loom-main', to: 'thread-ai', kind: 'links', label: 'extends' },
    { id: 'edge-4', from: 'thread-mechanics', to: 'evidence-one', kind: 'supports', label: 'proves' },
    { id: 'edge-5', from: 'idea-fabric', to: 'decision-one', kind: 'promotes', label: 'stitches into' },
    { id: 'edge-6', from: 'thread-ai', to: 'idea-fabric', kind: 'supports', label: 'makes visible' },
    { id: 'edge-7', from: 'stitch-one', to: 'decision-one', kind: 'supports', label: 'commits' },
  ],
};
